"""End-to-end: load each example file, fit it, and recover the known time.

The example datasets in ``examples/`` were generated by the forward model with
a known time (see ``scripts/make_examples.py``), so this exercises the whole
chain -- loader, column mapping, coefficient, solver, fit -- against an answer
that is known exactly.
"""
from pathlib import Path

import numpy as np
import pandas as pd
import pytest

from diffusor.coefficients import Conditions, get
from diffusor.constants import SEC_PER_DAY, SEC_PER_YEAR
from diffusor.dataio import ProfileSpec, build_profile, calibrate, read_table
from diffusor.fitting import DiffusionModel, fit_time
from diffusor.solvers import Geometry, InitialCondition, dirichlet
from diffusor.solvers.initial import guess_step_from_data
from diffusor.thermo import log_fo2_from_delta

EXAMPLES = Path(__file__).resolve().parents[1] / "examples"
pytestmark = pytest.mark.skipif(not EXAMPLES.exists(),
                                reason="run scripts/make_examples.py first")


def _fit(path, spec, coef_key, cond, comp_key=None, n_nodes=301):
    prof = build_profile(read_table(EXAMPLES / path), spec, str(path))
    ic = guess_step_from_data(prof.x, prof.C)
    model = DiffusionModel(
        coefficient=get(coef_key), conditions=cond, initial=ic, geometry=Geometry("plane"),
        bc_left=dirichlet(ic.params["C_left"]), bc_right=dirichlet(ic.params["C_right"]),
        comp_key=comp_key, composition_dependent=bool(comp_key), n_nodes=n_nodes)
    return fit_time(model, prof.x, prof.C, prof.sigma, free_parameters=("t", "x0")), prof


def test_opx_example_recovers_1_5_years():
    T = 950 + 273.15
    cond = Conditions(T_K=T, P_Pa=1.5e8, log_fo2_bar=log_fo2_from_delta("NNO", 1.0, T),
                      X={"XFe": 0.28}, axis="c")
    spec = ProfileSpec("Distance_um", "FeO_wt", "MgO_wt", "FeO_err", "MgO_err",
                       mode="A/(A+B)", oxide_a="FeO", oxide_b="MgO")
    r, prof = _fit("opx_femg_step.csv", spec, "opx_FeMg_dias2025", cond, comp_key="XFe")
    assert 0.6 < r.t_seconds / (1.5 * SEC_PER_YEAR) < 1.7
    assert r.stats.r_squared > 0.97


def test_cpx_example_recovers_45_days():
    cond = Conditions(T_K=1100 + 273.15, P_Pa=2.0e8, X={"XFe": 0.15})
    spec = ProfileSpec("Distance_um", "FeO_wt", "MgO_wt", "FeO_err", "MgO_err",
                       mode="A/(A+B)", oxide_a="FeO", oxide_b="MgO")
    r, _ = _fit("cpx_femg_step.csv", spec, "cpx_FeMg_muller2013", cond)
    assert 0.5 < r.t_seconds / (45 * SEC_PER_DAY) < 2.0
    assert r.stats.r_squared > 0.97


def test_plag_example_recovers_20_years():
    cond = Conditions(T_K=900 + 273.15, P_Pa=1.0e8, X={"XAn": 0.55})
    spec = ProfileSpec("Distance_um", "Mg_ppm", None, "Mg_err", mode="A")
    r, _ = _fit("plag_mg_an.csv", spec, "plag_Mg_vanorman2014", cond)
    assert 0.5 < r.t_seconds / (20 * SEC_PER_YEAR) < 2.0


def test_warning_fires_when_the_diffusion_length_eats_the_profile():
    """A profile whose plateaus have relaxed no longer satisfies the
    semi-infinite assumption, and the model must say so."""
    cond = Conditions(T_K=900 + 273.15, P_Pa=1.0e8, X={"XAn": 0.55})
    spec = ProfileSpec("Distance_um", "Mg_ppm", None, "Mg_err", mode="A")
    prof = build_profile(read_table(EXAMPLES / "plag_mg_an.csv"), spec)
    ic = guess_step_from_data(prof.x, prof.C)
    model = DiffusionModel(
        coefficient=get("plag_Mg_vanorman2014"), conditions=cond, initial=ic,
        geometry=Geometry("plane"), bc_left=dirichlet(ic.params["C_left"]),
        bc_right=dirichlet(ic.params["C_right"]), n_nodes=301,
        x_grid=np.linspace(prof.x.min(), prof.x.max(), 301))
    w = model.warnings(t_seconds=3000.0 * SEC_PER_YEAR)
    assert any("semi-infinite assumption" in s for s in w)


def test_magnetite_example_recovers_8_days():
    cond = Conditions(T_K=950 + 273.15, P_Pa=1.0e5, log_fo2_bar=-11.0, X={"xTi": 0.1})
    spec = ProfileSpec("Distance_um", "TiO2_wt", None, "TiO2_err", mode="A")
    r, _ = _fit("magnetite_ti.csv", spec, "mt_Ti_vanorman_crispin2010", cond)
    assert 0.4 < r.t_seconds / (8 * SEC_PER_DAY) < 2.5


def test_olivine_example_recovers_120_days():
    T = 1150 + 273.15
    cond = Conditions(T_K=T, P_Pa=1.0e5, log_fo2_bar=log_fo2_from_delta("FMQ", -1.0, T),
                      X={"XFe": 0.15}, axis="c")
    spec = ProfileSpec("Distance_um", "Fo_mol", None, "Fo_err", mode="A")
    prof = build_profile(read_table(EXAMPLES / "olivine_fo.csv"), spec)
    # the file stores Fo in mol%, the coefficient needs X_Fe
    xfe = 1.0 - prof.C / 100.0
    ic = guess_step_from_data(prof.x, xfe)
    model = DiffusionModel(
        coefficient=get("ol_FeMg_dohmen_chakraborty2007_tamed"), conditions=cond, initial=ic,
        geometry=Geometry("plane"), bc_left=dirichlet(ic.params["C_left"]),
        bc_right=dirichlet(ic.params["C_right"]), comp_key="XFe", n_nodes=301)
    r = fit_time(model, prof.x, xfe, prof.sigma / 100.0, free_parameters=("t", "x0"))
    assert 0.4 < r.t_seconds / (120 * SEC_PER_DAY) < 2.5


def test_greyscale_example_calibrates_and_fits():
    anchors = pd.read_csv(EXAMPLES / "cpx_greyscale_anchors.csv")
    cal = calibrate(anchors["GreyValue"], anchors["XFe_probe"], degree=1)
    # the generating response was X_Fe = (grey - 90)/620
    assert cal.coefficients[0] == pytest.approx(1.0 / 620.0, rel=0.1)
    assert cal.r_squared > 0.99

    df = pd.read_csv(EXAMPLES / "cpx_greyscale.csv")
    from diffusor.dataio import apply_calibration
    x, C, sigma = apply_calibration(df["Distance_um"], df["GreyValue"], cal, df["Grey_sd"])
    cond = Conditions(T_K=1000 + 273.15, P_Pa=2.0e8, X={"XFe": 0.15})
    ic = guess_step_from_data(x, C)
    model = DiffusionModel(coefficient=get("cpx_FeMg_muller2013"), conditions=cond, initial=ic,
                           geometry=Geometry("plane"), bc_left=dirichlet(ic.params["C_left"]),
                           bc_right=dirichlet(ic.params["C_right"]), n_nodes=301)
    r = fit_time(model, x, C, sigma, free_parameters=("t", "x0"))
    assert 0.5 < r.t_seconds / (3.0 * SEC_PER_YEAR) < 2.0


def test_comparing_two_coefficients_gives_different_times():
    """The whole point of the comparison mode: different published coefficients
    give materially different timescales for the same profile."""
    T = 950 + 273.15
    cond = Conditions(T_K=T, P_Pa=1.5e8, log_fo2_bar=log_fo2_from_delta("NNO", 1.0, T),
                      X={"XFe": 0.28}, axis="c")
    spec = ProfileSpec("Distance_um", "FeO_wt", "MgO_wt", "FeO_err", "MgO_err",
                       mode="A/(A+B)", oxide_a="FeO", oxide_b="MgO")
    times = {}
    for key in ("opx_FeMg_dohmen2016", "opx_FeMg_ganguly_tazzoli1994"):
        r, _ = _fit("opx_femg_step.csv", spec, key, cond, comp_key="XFe")
        times[key] = r.t_seconds
    ratio = max(times.values()) / min(times.values())
    assert ratio > 1.5, "the two opx calibrations should not agree closely"
