"""Generate references.bib and REFERENCES.md from the single citation registry.

Run from the project root:  python scripts/build_references.py
"""
from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from diffusor.coefficients import list_coefficients            # noqa: E402
from diffusor.references import REFERENCES, bibtex_document    # noqa: E402
from diffusor.thermo.buffers import BUFFER_CITATIONS           # noqa: E402


def build_bib() -> str:
    return bibtex_document()


def build_md() -> str:
    used = {}
    for c in list_coefficients():
        used.setdefault(c.citation, []).append(c.key)
        for k in c.secondary_citations:
            used.setdefault(k, []).append(c.key + " (secondary)")

    L = ["# References",
         "",
         "Generated by `scripts/build_references.py` from `diffusor/references.py`.",
         "Every equation, coefficient, constant and convention in Diffusor points at one of",
         "these keys, and the test suite fails if a citation key does not resolve.",
         "",
         "## Diffusion coefficients in the registry",
         "",
         "| key | mineral | species | source | verified |",
         "| --- | --- | --- | --- | --- |"]
    for c in list_coefficients():
        L.append(f"| `{c.key}` | {c.mineral} | {c.species} | "
                 f"{REFERENCES[c.citation].short()} | {'yes' if c.verified else '**NO**'} |")

    L += ["",
          "Entries marked **NO** were transcribed from a secondary source because the primary",
          "publication was not available offline. Each one records where its numbers came from",
          "in its `verified_from` field, which is printed in the application and written into",
          "every exported methods block. Check them against the primary paper before publishing.",
          "",
          "## Oxygen fugacity buffers",
          ""]
    for name, key in BUFFER_CITATIONS.items():
        L.append(f"- **{name}**: {REFERENCES[key].full()}")

    L += ["", "## Full bibliography", ""]
    for key in sorted(REFERENCES):
        r = REFERENCES[key]
        line = f"- **`{key}`** {r.full()}"
        if key in used:
            line += f"\n  - used by: {', '.join(sorted(set(used[key])))}"
        L.append(line)
    L.append("")
    return "\n".join(L)


def main():
    (ROOT / "references.bib").write_text(build_bib(), encoding="utf-8")
    (ROOT / "REFERENCES.md").write_text(build_md(), encoding="utf-8")
    print(f"wrote references.bib and REFERENCES.md ({len(REFERENCES)} references, "
          f"{len(list_coefficients())} coefficients)")


if __name__ == "__main__":
    main()
