"""What an input file has to look like, in one place.

Shown on the data step of the interface and reproduced in the README, so the
answer to "does it have to be formatted in a certain way?" is always to hand.
"""
from __future__ import annotations

SHORT = ("One row per measurement point. One column of distance, one or two columns of "
         "composition, and optionally a column of uncertainty for each. Column names are "
         "free: you map them yourself on the next screen.")

FILE_TYPES = ".csv, .txt, .tsv (any delimiter) or .xlsx / .xls"

EXAMPLE_TABLE = """Distance_um,FeO_wt,MgO_wt,FeO_err,MgO_err
0.0,20.9,22.4,0.15,0.20
1.7,20.8,22.5,0.15,0.20
3.3,21.0,22.3,0.15,0.20
...,...,...,...,..."""

RULES = [
    ("Distance column",
     "Required. Any units, you choose them when mapping (um, mm, nm or m). It may start at "
     "zero or not, and it may run rim-to-core or core-to-rim; Diffusor sorts it either way. "
     "Spacing does not have to be even."),
    ("Composition columns",
     "One or two. With two, Diffusor forms the molar ratio A/(A+B), which is what the "
     "diffusion coefficients are calibrated against, for example FeO and MgO wt% giving "
     "X_Fe. With one, the column is modelled as it stands, which suits a trace element in "
     "ppm, a forsterite content in mol% or a calibrated grey value."),
    ("Uncertainty columns",
     "Optional but strongly recommended. Without them every point is weighted equally and "
     "the reported chi-squared is only a relative measure. You say whether they are 1 sigma "
     "or 2 sigma when mapping; 2 sigma values are halved."),
    ("Oxide conversion",
     "If your composition columns are oxide weight per cent, name the oxides when mapping "
     "(FeO, MgO, CaO, Na2O and so on). Diffusor then converts to cation moles before taking "
     "the ratio, using the IUPAC 2021 atomic weights. Skip it and the ratio is taken on the "
     "raw numbers, which is wrong for wt% data."),
    ("Extra columns",
     "Ignored, so you can keep anything else in the file. A plagioclase anorthite column is "
     "worth keeping: it lets you switch on the activity term that couples trace-element "
     "diffusion to the anorthite gradient."),
    ("Missing values",
     "Blank or non-numeric cells are dropped, and you are told how many. Non-positive "
     "uncertainties are replaced by the median and flagged."),
]

GREYSCALE = (
    "BSE grey values are supported, but they are never fitted raw. Load the grey profile, "
    "then supply at least two microprobe anchor points so Diffusor can calibrate grey value "
    "to composition and propagate the calibration uncertainty. The residuals of that "
    "calibration are reported, so a non-linear response is visible rather than hidden.")

NO_DATA = (
    "No data of your own yet? Load one of the bundled datasets below. One is a real measured "
    "profile from a published paper; the others were generated by Diffusor's own forward "
    "model with a known answer, and are labelled as such wherever they appear.")


def as_plain_text() -> str:
    lines = ["INPUT FILE FORMAT", "=" * 60, "", SHORT, "", f"Accepted files: {FILE_TYPES}", "",
             "Example:", "", EXAMPLE_TABLE, ""]
    for title, body in RULES:
        lines += [f"{title}", f"    {body}", ""]
    lines += ["Greyscale profiles", f"    {GREYSCALE}", ""]
    return "\n".join(lines)
